tone_mapping = {
    "affectionate": {"chinese": "充满爱意的", "pinyin": "chōngmǎn àiyì de"},
    "angry": {"chinese": "生气的", "pinyin": "shēngqì de"},
    "annoyed": {"chinese": "恼怒的", "pinyin": "nǎonù de"},
    "anxious": {"chinese": "焦虑的", "pinyin": "jiāolǜ de"},
    "bored": {"chinese": "无聊的", "pinyin": "wúliáo de"},
    "calm": {"chinese": "平静的", "pinyin": "píngjìng de"},
    "cheerful": {"chinese": "愉快的", "pinyin": "yúkuài de"},
    "confident": {"chinese": "自信的", "pinyin": "zìxìn de"},
    "confused": {"chinese": "困惑的", "pinyin": "kùnhuò de"},
    "cynical": {"chinese": "愤世嫉俗的", "pinyin": "fèn shì jì sú de"},
    "defensive": {"chinese": "防御的", "pinyin": "fángyù de"},
    "desperate": {"chinese": "绝望的", "pinyin": "juéwàng de"},
    "determined": {"chinese": "坚定的", "pinyin": "jiāndìng de"},
    "disappointed": {"chinese": "失望的", "pinyin": "shīwàng de"},
    "disgusted": {"chinese": "厌恶的", "pinyin": "yànwù de"},
    "enthusiastic": {"chinese": "热情的", "pinyin": "rèqíng de"},
    "excited": {"chinese": "兴奋的", "pinyin": "xīngfèn de"},
    "fearful": {"chinese": "害怕的", "pinyin": "hàipà de"},
    "friendly": {"chinese": "友好的", "pinyin": "yǒuhǎo de"},
    "frustrated": {"chinese": "沮丧的", "pinyin": "jǔsàng de"},
    "grateful": {"chinese": "感激的", "pinyin": "gǎnjī de"},
    "hopeful": {"chinese": "充满希望的", "pinyin": "chōngmǎn xīwàng de"},
    "humorous": {"chinese": "幽默的", "pinyin": "yōumò de"},
    "impatient": {"chinese": "不耐烦的", "pinyin": "bù nàifán de"},
    "indifferent": {"chinese": "冷漠的", "pinyin": "lěngmò de"},
    "inquisitive": {"chinese": "好奇的", "pinyin": "hàoqí de"},
    "inspirational": {"chinese": "鼓舞人心的", "pinyin": "gǔwǔ rénxīn de"},
    "jealous": {"chinese": "嫉妒的", "pinyin": "jídù de"},
    "joyful": {"chinese": "欢乐的", "pinyin": "huānlè de"},
    "melancholic": {"chinese": "忧郁的", "pinyin": "yōuyù de"},
    "mocking": {"chinese": "嘲讽的", "pinyin": "cháofěng de"},
    "motivational": {"chinese": "激励的", "pinyin": "jīlì de"},
    "neutral": {"chinese": "中性的", "pinyin": "zhōngxìng de"},
    "nostalgic": {"chinese": "怀旧的", "pinyin": "huáijiù de"},
    "optimistic": {"chinese": "乐观的", "pinyin": "lèguān de"},
    "pessimistic": {"chinese": "悲观的", "pinyin": "bēiguān de"},
    "playful": {"chinese": "爱玩的", "pinyin": "àiwán de"},
    "sarcastic": {"chinese": "讽刺的", "pinyin": "fěngcì de"},
    "serious": {"chinese": "严肃的", "pinyin": "yánsù de"},
    "skeptical": {"chinese": "怀疑的", "pinyin": "huáiyí de"},
    "somber": {"chinese": "阴郁的", "pinyin": "yīnyù de"},
    "sympathetic": {"chinese": "同情的", "pinyin": "tóngqíng de"},
    "tender": {"chinese": "温柔的", "pinyin": "wēnróu de"},
    "teasing": {"chinese": "取笑的", "pinyin": "qǔxiào de"},
    "tense": {"chinese": "紧张的", "pinyin": "jǐnzhāng de"},
    "thoughtful": {"chinese": "体贴的", "pinyin": "tǐtiē de"},
    "urgent": {"chinese": "紧急的", "pinyin": "jǐnjí de"},
    "warm": {"chinese": "温暖的", "pinyin": "wēnnuǎn de"},
    "whimsical": {"chinese": "异想天开的", "pinyin": "yìxiǎngtiānkāi de"},
    "worried": {"chinese": "担心的", "pinyin": "dānxīn de"},

    # Additional Expressions
    "professional": {"chinese": "专业的", "pinyin": "zhuānyè de"},
    "formal": {"chinese": "正式的", "pinyin": "zhèngshì de"},
    "informal": {"chinese": "非正式的", "pinyin": "fēi zhèngshì de"},
    "assertive": {"chinese": "自信坚定的", "pinyin": "zìxìn jiāndìng de"},
    "humble": {"chinese": "谦虚的", "pinyin": "qiānxū de"},
    "respectful": {"chinese": "尊重的", "pinyin": "zūnzhòng de"},
    "casual": {"chinese": "随意的", "pinyin": "suíyì de"},
    "encouraging": {"chinese": "鼓励的", "pinyin": "gǔlì de"},
    "authoritative": {"chinese": "权威的", "pinyin": "quánwēi de"},
    "compassionate": {"chinese": "富有同情心的", "pinyin": "fù yǒu tóngqíng xīn de"},
    "sincere": {"chinese": "真诚的", "pinyin": "zhēnchéng de"},
    "elegant": {"chinese": "优雅的", "pinyin": "yōuyǎ de"},
    "romantic": {"chinese": "浪漫的", "pinyin": "làngmàn de"},
    "light-hearted": {"chinese": "轻松愉快的", "pinyin": "qīngsōng yúkuài de"},
    "frivolous": {"chinese": "轻浮的", "pinyin": "qīngfú de"},
    "cautious": {"chinese": "谨慎的", "pinyin": "jǐnshèn de"},
    "bold": {"chinese": "大胆的", "pinyin": "dàdǎn de"},
    "quirky": {"chinese": "古怪的", "pinyin": "gǔguài de"},
    "reflective": {"chinese": "反思的", "pinyin": "fǎnsī de"},
    "energetic": {"chinese": "充满活力的", "pinyin": "chōngmǎn huólì de"},
    "dynamic": {"chinese": "有活力的", "pinyin": "yǒu huólì de"},
    "relaxed": {"chinese": "放松的", "pinyin": "fàngsōng de"},
    "intense": {"chinese": "紧张激烈的", "pinyin": "jǐnzhāng jīliè de"},
    "peaceful": {"chinese": "和平的", "pinyin": "hépíng de"},
    "aggressive": {"chinese": "好斗的", "pinyin": "hǎodòu de"},
    "passionate": {"chinese": "充满激情的", "pinyin": "chōngmǎn jīqíng de"},
    "sad": {"chinese": "悲伤的", "pinyin": "bēishāng de"},
}
